# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
my:
 profile: default
 
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bezkoder_db
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: =org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
       dialect:
       storage_engine: innodb
   
  flyway:
   schema: bezkoder_db
   locations: classpath:db/migration
   baseline-version: 1.0
   validate-on-migrate: true
   enabled: true
   encoding: UTF-8